include: "rules/common.smk"


rule all:
    input:
        expand("results/{sample}/ragtag/", sample=SAMPLES),
        # expand("results/{sample}/mapped/{sample}.sorted.bam.flagstat", sample=SAMPLES),
        # expand("results/{sample}/mapped/{sample}.sorted.bam.idxstats", sample=SAMPLES),
        expand("results/{sample}/lineage_assignment/{sample}.csv", sample=SAMPLES),
        expand("workflow/report/{sample}/{sample}_variants.html", sample=SAMPLES)


include: "rules/preprocess.smk"
include: "rules/de-novo.smk"
include: "rules/aligning.smk"
include: "rules/calling.smk"
include: "rules/lineage_assignment.smk"
include: "rules/generate_report.smk"
