samples:
    [RV417026_S15_L001, RV417027_S18_L001]

reference_genome:
    reference

adapter:
    read_1: "GCGAATTTCGACGATCGTTGCATTAACTCGCGAA"
    read_2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"

rule_parameters:
    bwa_index:
        algorithm: "bwstw"
    bwa_mem:
        sorting: "none"
    samtools_sort:
        extra: "-m 4G"
    samtools_index:
        extra: ""
    samtools_flagstat:
        extra: ""
    samtools_idxstats:
        extra: ""
    bcftools_mpileup:
        uncompressed_bcf: False
        extra: "--max-depth 100 --min-BQ 15"
    bcftools_call:
        caller: "-m"
        extra: "--ploidy 1 -v"
    filter_vcf:
        extra: ""