from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/DSiB-G2/G2-CovPipeline as a module
module G2_CovPipeline:
    snakefile: 
        github("DSiB-G2/G2-CovPipeline", path="workflow/Snakefile", tag="v1.0")
    config:
        config


# use all rules from https://github.com/DSiB-G2/G2-CovPipeline
use rule * from G2_CovPipeline
