name: Tests

on:
  push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.test'
        snakefile: workflow/Snakefile
        args: '--lint'
  test-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
    - name: Test
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.test'
        snakefile: workflow/Snakefile
        args: "--use-conda --cores 1 --conda-cleanup-pkgs cache"